"""Assemble the dashboard payload from the per-cell archive.

Outputs (all generated, all gitignored — CI rebuilds them before Pages deploy):
  site/data.js        one JS global. Day-arrays are stored ONCE PER CELL and
                      pincodes reference their cell — that keeps 15k pincodes
                      to a ~2 MB payload instead of ~15 MB.
  site/hist/<XX>.json history shards (D1 forecast vs observed, last 30 days),
                      keyed by 2-digit pincode prefix, fetched on demand when
                      a detail drawer opens.

Run:  python scripts/build_site.py
"""
from __future__ import annotations

import csv
import json
import os
import shutil
from collections import defaultdict
from datetime import timedelta

import common as C

HISTORY_DAYS = 30
BAND_CODE = {"NONE": 0, "WATCH": 1, "ACT": 2}


def load_forecasts():
    """Return (latest_run, run_ts, latest_cell_days, d1_index).

    latest_cell_days: cell_id -> [ [mm,p10,p90,p30,p60,bcode] for D0..D6 ]
    d1_index: (valid_date, cell_id) -> (forecast_mm, bcode)
    """
    files = C.archive_files(C.FORECASTS)
    if not files:
        raise SystemExit("No forecast files found. Run the pipeline first.")
    latest_path = files[-1]
    latest_run = C.file_date(latest_path)

    d1_index = {}
    for path in files:
        with C.open_text(path) as f:
            for r in csv.DictReader(f):
                if r["lead_day"] == "1":
                    d1_index[(r["valid_date"], r["cell_id"])] = (
                        float(r["rain_mm_median"]), BAND_CODE[r["band"]])

    cell_days = defaultdict(lambda: [None] * (C.MAX_LEAD + 1))
    run_ts = None
    with C.open_text(latest_path) as f:
        for r in csv.DictReader(f):
            run_ts = r["run_ts_ist"]
            cell_days[r["cell_id"]][int(r["lead_day"])] = [
                float(r["rain_mm_median"]), float(r["rain_mm_p10"]),
                float(r["rain_mm_p90"]), float(r["prob_gt30"]),
                float(r["prob_gt60"]), BAND_CODE[r["band"]],
            ]
    return latest_run, run_ts, dict(cell_days), d1_index


def load_observed_recent(latest, days=HISTORY_DAYS):
    """(pincode, iso_date) -> mm for the trailing window only."""
    cutoff = C.parse_date(latest) - timedelta(days=days + 1)
    obs = {}
    for path in C.archive_files(C.OBSERVED):
        if C.parse_date(C.file_date(path)) < cutoff:
            continue
        with C.open_text(path) as f:
            for r in csv.DictReader(f):
                obs[(r["pincode"], r["date"])] = float(r["observed_mm"])
    return obs


def main():
    pincodes = C.load_pincodes()
    priority = C.load_priority()
    hubs = C.load_hubs()
    latest_run, run_ts, cell_days, d1_index = load_forecasts()
    obs = load_observed_recent(latest_run)
    latest = C.parse_date(latest_run)

    # --- history shards ------------------------------------------------------
    hist_dir = C.SITE / "hist"
    if hist_dir.exists():
        shutil.rmtree(hist_dir)
    hist_dir.mkdir(parents=True)
    shards = defaultdict(dict)
    for p in pincodes:
        pin, cell = p["pincode"], p["cell_id"]
        rows = []
        for i in range(HISTORY_DAYS, 0, -1):
            v = latest - timedelta(days=i)
            if v < C.ARCHIVE_START:
                continue
            vs = C.iso(v)
            o = obs.get((pin, vs))
            fc = d1_index.get((vs, cell))
            if o is None or fc is None:
                continue
            rows.append([vs, o, fc[0], fc[1]])
        if rows:
            shards[pin[:2]][pin] = rows
    for prefix, data in shards.items():
        with open(hist_dir / f"{prefix}.json", "w", encoding="utf-8") as f:
            json.dump(data, f, separators=(",", ":"))

    # --- verification --------------------------------------------------------
    ver = {}
    vpath = C.VERIFICATION / "summary.json"
    if vpath.exists():
        ver = json.loads(vpath.read_text(encoding="utf-8"))

    # --- payload -------------------------------------------------------------
    pins = [[p["pincode"], p["area"], p["state"], p["lat"], p["lon"],
             p["cell_id"], 1 if p["pincode"] in priority else 0]
            for p in pincodes]
    hub_rows = [[h["hub_city"], h["cell_id"], h["lat"], h["lon"]] for h in hubs]

    payload = dict(
        run_mode=os.environ.get("RAINOPS_MODE", "sample").upper(),
        generated_ist=run_ts,
        archive_start=str(C.ARCHIVE_START),
        thresholds=dict(p30_watch=C.P30_WATCH, p60_act=C.P60_ACT,
                        imd_heavy_mm=C.IMD_HEAVY_MM, event_mm=C.EVENT_MM),
        meta=dict(n_pincodes=len(pincodes), n_cells=len(cell_days),
                  latest_run=latest_run, history_days=HISTORY_DAYS),
        verification=ver,
        hubs=hub_rows,
        cells=cell_days,
        pins=pins,
    )

    C.SITE.mkdir(parents=True, exist_ok=True)
    out = C.SITE / "data.js"
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_site.py — do not edit.\n")
        f.write("window.__RAINOPS__ = ")
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    size_mb = out.stat().st_size / 1e6
    hist_mb = sum(p.stat().st_size for p in hist_dir.glob("*.json")) / 1e6
    print(f"[build] data.js {size_mb:.1f} MB ({len(pins)} pins, {len(cell_days)} cells) | "
          f"hist shards: {len(shards)} files, {hist_mb:.1f} MB | run {latest_run} @ {run_ts}")


if __name__ == "__main__":
    main()
